server:
  port: 8080
  
spring:
 application:
  name: url-shortner-app
  
 datasource:
  url: jdbc:postgresql://localhost:5432/urlshortner
  username: ${SPRING_DATASOURCE_USERNAME:postgres}
  password:  ${SPRING_DATASOURCE_PASSWORD:password}
 jpa:
  open-in-view: false
  hibernate:
   ddl-auto: update
  show-sql: true 
